version: 0.2

env:
  secrets-manager:
    LOGIN: newsecrets:sonartoken
    HOST: newsecrets:HOST
    Organization: newsecrets:Organization
    Project: newsecrets:Project
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get install -y unzip
      
  pre_build:
    commands:
      - echo "Pre build phase ..."
      - apt-get install -y unzip
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - echo "Current path is >>>"
      - sh $pwd
      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
      - ls $pwd
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
  build:
    commands:
      - echo "Build phase ..."
      - zip hello.zip ./index.html ./aws.gif ./1.png ./back.jpg
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
