version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
